# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sandbox_pb2 as sandbox__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/photon.sandbox.SandboxService/Execute',
                request_serializer=sandbox__pb2.SandboxRequest.SerializeToString,
                response_deserializer=sandbox__pb2.SandboxResponse.FromString,
                _registered_method=True)
        self.ExecuteAsync = channel.unary_unary(
                '/photon.sandbox.SandboxService/ExecuteAsync',
                request_serializer=sandbox__pb2.SandboxRequest.SerializeToString,
                response_deserializer=sandbox__pb2.AsyncResponse.FromString,
                _registered_method=True)
        self.GetPoolStatus = channel.unary_unary(
                '/photon.sandbox.SandboxService/GetPoolStatus',
                request_serializer=sandbox__pb2.EmptyRequest.SerializeToString,
                response_deserializer=sandbox__pb2.PoolStatusResponse.FromString,
                _registered_method=True)
        self.GetTaskResult = channel.unary_unary(
                '/photon.sandbox.SandboxService/GetTaskResult',
                request_serializer=sandbox__pb2.TaskResultRequest.SerializeToString,
                response_deserializer=sandbox__pb2.TaskResultResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """同步执行任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAsync(self, request, context):
        """异步执行任务（不等待结果，通过回调或轮询获取）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoolStatus(self, request, context):
        """获取池状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskResult(self, request, context):
        """查询异步任务结果（ExecuteAsync 提交后用 task_id 查询）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=sandbox__pb2.SandboxRequest.FromString,
                    response_serializer=sandbox__pb2.SandboxResponse.SerializeToString,
            ),
            'ExecuteAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAsync,
                    request_deserializer=sandbox__pb2.SandboxRequest.FromString,
                    response_serializer=sandbox__pb2.AsyncResponse.SerializeToString,
            ),
            'GetPoolStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoolStatus,
                    request_deserializer=sandbox__pb2.EmptyRequest.FromString,
                    response_serializer=sandbox__pb2.PoolStatusResponse.SerializeToString,
            ),
            'GetTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskResult,
                    request_deserializer=sandbox__pb2.TaskResultRequest.FromString,
                    response_serializer=sandbox__pb2.TaskResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photon.sandbox.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photon.sandbox.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.sandbox.SandboxService/Execute',
            sandbox__pb2.SandboxRequest.SerializeToString,
            sandbox__pb2.SandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.sandbox.SandboxService/ExecuteAsync',
            sandbox__pb2.SandboxRequest.SerializeToString,
            sandbox__pb2.AsyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoolStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.sandbox.SandboxService/GetPoolStatus',
            sandbox__pb2.EmptyRequest.SerializeToString,
            sandbox__pb2.PoolStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.sandbox.SandboxService/GetTaskResult',
            sandbox__pb2.TaskResultRequest.SerializeToString,
            sandbox__pb2.TaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuditServiceStub:
    """===== 审计日志批量上报（Client Streaming）=====
    沙盒节点侧异步队列攒批，通过客户端流式 RPC 一次发送多条审计记录；
    比逐条 unary 调用减少 RTT，适合高吞吐审计上报场景。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchReport = channel.stream_unary(
                '/photon.sandbox.AuditService/BatchReport',
                request_serializer=sandbox__pb2.AuditRecord.SerializeToString,
                response_deserializer=sandbox__pb2.BatchReportResp.FromString,
                _registered_method=True)


class AuditServiceServicer:
    """===== 审计日志批量上报（Client Streaming）=====
    沙盒节点侧异步队列攒批，通过客户端流式 RPC 一次发送多条审计记录；
    比逐条 unary 调用减少 RTT，适合高吞吐审计上报场景。
    """

    def BatchReport(self, request_iterator, context):
        """客户端流式批量上报：客户端连续 Write 多条 AuditRecord，结束后服务端返回汇总应答
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchReport': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchReport,
                    request_deserializer=sandbox__pb2.AuditRecord.FromString,
                    response_serializer=sandbox__pb2.BatchReportResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photon.sandbox.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photon.sandbox.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService:
    """===== 审计日志批量上报（Client Streaming）=====
    沙盒节点侧异步队列攒批，通过客户端流式 RPC 一次发送多条审计记录；
    比逐条 unary 调用减少 RTT，适合高吞吐审计上报场景。
    """

    @staticmethod
    def BatchReport(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/photon.sandbox.AuditService/BatchReport',
            sandbox__pb2.AuditRecord.SerializeToString,
            sandbox__pb2.BatchReportResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
